#   Makefile
#
#   License   http://opensource.org/licenses/MIT The MIT License (MIT)
#

.PHONY: clean install example

clean:
	rm -fR __pycache__
	rm -fR *.pyc
	rm -fR tmp

example: clean
	python3 example_countries.py
